### ISSUE TITLE
Stuck on exercise 5

### ISSUE THREAD

**Issue by finnpedersenkazes** [zwilias/elm-demystify-decoders#6]
Dear Ilias Van Peer

First of all, thank you for having made this. I really had a hard time understanding decoders in Elm and given the importance, I was looking for ways get some intuition for it. I have cloned the project and solved 1, 2, 3, 4, 6, 7, 8, 9 and 11. So far so good. 

I write because, I am hopelessly stuck on number 5. 
Could you give some kind of hint? Please. 

https://github.com/finnpedersenkazes/elm-demystify-decoders

Kind regards
Finn

**Comment by pdamoc** [comment]
Hint: you need to use a function that you have already imported. There are 226 words in that file. If you add one more you're done. ;)

**Comment by finnpedersenkazes** [comment]
Thank you so much. I finally got it. I don't know why I had such a hard time with the map2 function, but this really helped me solve number 10 as well. Cheers.
